'use client';
import dynamic from 'next/dynamic';
import { Loader2 } from 'lucide-react';
const PdfSplitter = dynamic(() => import('@/components/PdfSplitter'), { ssr: false, loading: () => (<div className="flex flex-col items-center justify-center min-h-[500px] gap-4 font-mono"><Loader2 className="w-10 h-10 animate-spin text-white" /><p className="text-zinc-400 font-mono text-xs">Cargando...</p></div>) });
import { ShieldCheck, Scissors, AlertTriangle } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';
export default function Page() { const { lang } = useLanguage(); const isEs = lang === 'es';
  return (<main className="w-full px-4 sm:px-6 lg:px-8 py-8 flex flex-col items-center justify-start min-h-[calc(100vh-100px)] bg-[#09090b]"><div className="w-full max-w-7xl"><PdfSplitter />
    <div className="space-y-8 text-zinc-300 font-sans border-t border-white/10 pt-10 mt-10">
      <div className="bg-[#09090b] border border-white/10 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-white/10 pb-4"><div className="bg-zinc-900 p-2.5 rounded-xl border border-white/10"><Scissors className="w-5 h-5 text-white" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'1. Cómo dividir un PDF':'1. How to split a PDF'}</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{[{step:'01',es:'Sube tu archivo PDF a la zona de carga.',en:'Upload your PDF to the upload zone.'},{step:'02',es:'Elige el modo: extraer páginas o dividir por rangos.',en:'Choose the mode: extract pages or split by ranges.'},{step:'03',es:'Define los rangos y configura el formato de salida (PDF o ZIP).',en:'Define ranges and configure output format (PDF or ZIP).'},{step:'04',es:'Haz clic en "Dividir PDF →" y descarga los archivos resultantes.',en:'Click "Split PDF →" and download the resulting files.'}].map((item,i)=>(<div key={i} className="bg-zinc-900/60 border border-white/5 rounded-xl p-4 flex flex-col gap-2"><span className="text-[10px] font-mono font-bold text-zinc-400 bg-zinc-900 border border-white/10 px-2 py-0.5 rounded-full w-fit">Paso {item.step}</span><p className="text-xs text-zinc-400 leading-relaxed">{isEs?item.es:item.en}</p></div>))}</div></div>
      <div className="bg-[#09090b] border border-amber-500/20 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-amber-500/20 pb-4"><div className="bg-amber-500/10 p-2.5 rounded-xl border border-amber-500/30"><AlertTriangle className="w-5 h-5 text-amber-400" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'2. Limitaciones y consejos útiles':'2. Limitations & useful tips'}</h2></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="space-y-3"><h4 className="text-xs font-mono text-emerald-400 font-bold uppercase tracking-wider border-b border-white/10 pb-2">✓ {isEs?'LO QUE PUEDES HACER':'WHAT YOU CAN DO'}</h4>{[isEs?'Extraer páginas específicas para crear nuevos documentos.':'Extract specific pages to create new documents.',isEs?'Dividir cada página en archivos PDF separados.':'Split each page into separate PDF files.',isEs?'Dividir por rangos personalizados y empaquetar en ZIP.':'Split by custom ranges and package in ZIP.',isEs?'Configurar sufijos y numeración automática.':'Configure suffixes and automatic numbering.'].map((t,i)=>(<div key={i} className="flex items-start gap-2 text-xs text-zinc-300"><span className="text-emerald-400 font-bold flex-shrink-0 mt-0.5">✓</span><span>{t}</span></div>))}</div><div className="space-y-3"><h4 className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider border-b border-white/10 pb-2">💡 {isEs?'CONSEJOS':'TIPS'}</h4>{[isEs?'Ideal para separar capítulos o facturas individuales de un lote.':'Ideal for separating chapters or individual invoices from a batch.',isEs?'Las páginas extraídas conservan la misma calidad original.':'Extracted pages retain the same original quality.',isEs?'Usa formato ZIP para descargar múltiples archivos de una vez.':'Use ZIP format to download multiple files at once.',isEs?'Procesa documentos de cientos de páginas sin límites.':'Process documents with hundreds of pages without limits.'].map((t,i)=>(<div key={i} className="flex items-start gap-2 text-xs text-zinc-300"><span className="text-amber-400 flex-shrink-0 mt-0.5">→</span><span>{t}</span></div>))}</div></div></div>
      <div className="bg-[#09090b] border border-emerald-500/20 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-emerald-500/20 pb-4"><div className="bg-emerald-500/10 p-2.5 rounded-xl border border-emerald-500/30"><ShieldCheck className="w-5 h-5 text-emerald-400" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'3. ¿Qué sucede con tu documento?':'3. What happens to your document?'}</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs text-zinc-400 leading-relaxed"><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">🖥️ {isEs?'Procesamiento 100% local':'100% local processing'}</strong><p className="text-[11px]">{isEs?'La división se ejecuta en la RAM de tu navegador.':'Splitting runs in your browser RAM.'}</p></div><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">✂️ {isEs?'Extracción sin pérdida de calidad':'Lossless extraction'}</strong><p className="text-[11px]">{isEs?'Páginas copiadas con copyPages(). Calidad y resolución intactas.':'Pages copied with copyPages(). Quality and resolution intact.'}</p></div><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">📥 {isEs?'Descarga directa y segura':'Direct & secure download'}</strong><p className="text-[11px]">{isEs?'Archivos generados localmente. Tu original no se modifica.':'Files generated locally. Your original is not modified.'}</p></div></div></div>
    </div>
  </div></main>);
}