'use client';
import dynamic from 'next/dynamic';
import { Loader2, ShieldCheck, Trash2, AlertTriangle } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';

const PdfPageDeleter = dynamic(() => import('@/components/PdfPageDeleter'), { ssr: false, loading: () => (<div className="flex flex-col items-center justify-center min-h-[500px] gap-4 font-mono"><Loader2 className="w-10 h-10 animate-spin text-white" /><p className="text-zinc-400 font-mono text-xs">Cargando...</p></div>) });

export default function Page() { const { lang } = useLanguage(); const isEs = lang === 'es';
  return (<main className="w-full px-4 sm:px-6 lg:px-8 py-8 flex flex-col items-center justify-start min-h-[calc(100vh-100px)] bg-[#09090b]"><div className="w-full max-w-7xl"><PdfPageDeleter />
    <div className="space-y-8 text-zinc-300 font-sans border-t border-white/10 pt-10 mt-10">
      <div className="bg-[#09090b] border border-white/10 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-white/10 pb-4"><div className="bg-zinc-900 p-2.5 rounded-xl border border-white/10"><Trash2 className="w-5 h-5 text-white" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'1. Cómo eliminar páginas':'1. How to delete pages'}</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{[{step:'01',es:'Sube tu PDF. El visor mostrará miniaturas de todas las páginas.',en:'Upload your PDF. The viewer will show thumbnails.'},{step:'02',es:'Selecciona las páginas a eliminar haciendo clic en cada miniatura.',en:'Select pages to delete by clicking on each thumbnail.'},{step:'03',es:'Usa filtros rápidos o rangos para seleccionar múltiples páginas.',en:'Use quick filters or ranges to select multiple pages.'},{step:'04',es:'Haz clic en "Eliminar Páginas →" y descarga el PDF resultante.',en:'Click "Delete Pages →" and download the resulting PDF.'}].map((item,i)=>(<div key={i} className="bg-zinc-900/60 border border-white/5 rounded-xl p-4 flex flex-col gap-2"><span className="text-[10px] font-mono font-bold text-zinc-400 bg-zinc-900 border border-white/10 px-2 py-0.5 rounded-full w-fit">Paso {item.step}</span><p className="text-xs text-zinc-400 leading-relaxed">{isEs?item.es:item.en}</p></div>))}</div></div>
      <div className="bg-[#09090b] border border-amber-500/20 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-amber-500/20 pb-4"><div className="bg-amber-500/10 p-2.5 rounded-xl border border-amber-500/30"><AlertTriangle className="w-5 h-5 text-amber-400" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'2. Limitaciones y consejos útiles':'2. Limitations & useful tips'}</h2></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="space-y-3"><h4 className="text-xs font-mono text-emerald-400 font-bold uppercase tracking-wider border-b border-white/10 pb-2">✓ {isEs?'LO QUE PUEDES HACER':'WHAT YOU CAN DO'}</h4>{[isEs?'Eliminar páginas no deseadas con selección visual.':'Delete unwanted pages with visual selection.',isEs?'Seleccionar múltiples páginas o usar rangos.':'Select multiple pages or use ranges.',isEs?'Filtrar páginas pares/impares o en blanco.':'Filter even/odd or blank pages.',isEs?'Previsualizar cada página antes de eliminar.':'Preview each page before deleting.'].map((t,i)=>(<div key={i} className="flex items-start gap-2 text-xs text-zinc-300"><span className="text-emerald-400 font-bold flex-shrink-0 mt-0.5">✓</span><span>{t}</span></div>))}</div><div className="space-y-3"><h4 className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider border-b border-white/10 pb-2">💡 {isEs?'CONSEJOS':'TIPS'}</h4>{[isEs?'Ideal para limpiar páginas en blanco o anexos no deseados.':'Ideal for cleaning blank pages or unwanted appendices.',isEs?'Las páginas restantes conservan la misma calidad.':'Remaining pages retain the same quality.',isEs?'El proceso genera un nuevo archivo. Tu original no se modifica.':'The process generates a new file. Your original is not modified.',isEs?'Usa el filtro de páginas en blanco para eliminarlas de una vez.':'Use the blank page filter to delete them all at once.'].map((t,i)=>(<div key={i} className="flex items-start gap-2 text-xs text-zinc-300"><span className="text-amber-400 flex-shrink-0 mt-0.5">→</span><span>{t}</span></div>))}</div></div></div>
      <div className="bg-[#09090b] border border-emerald-500/20 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-emerald-500/20 pb-4"><div className="bg-emerald-500/10 p-2.5 rounded-xl border border-emerald-500/30"><ShieldCheck className="w-5 h-5 text-emerald-400" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'3. ¿Qué sucede con tu documento?':'3. What happens to your document?'}</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs text-zinc-400 leading-relaxed"><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">🖥️ {isEs?'Procesamiento 100% local':'100% local processing'}</strong><p className="text-[11px]">{isEs?'La eliminación se ejecuta en la RAM de tu navegador.':'Deletion runs in your browser RAM.'}</p></div><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">🗑️ {isEs?'Eliminación sin pérdida de calidad':'Deletion without quality loss'}</strong><p className="text-[11px]">{isEs?'Solo las páginas seleccionadas se eliminan. El resto intacto.':'Only selected pages are removed. The rest intact.'}</p></div><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">📥 {isEs?'Descarga directa y segura':'Direct & secure download'}</strong><p className="text-[11px]">{isEs?'El PDF se genera localmente. Tu original no se modifica.':'The PDF is generated locally. Your original is not modified.'}</p></div></div></div>
    </div>
  </div></main>);
}