'use client';
import dynamic from 'next/dynamic';
import { Loader2, ShieldCheck, Merge, AlertTriangle } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';

const PdfMerger = dynamic(() => import('@/components/PdfMerger'), { ssr: false, loading: () => (<div className="flex flex-col items-center justify-center min-h-[500px] gap-4 font-mono"><Loader2 className="w-10 h-10 animate-spin text-white" /><p className="text-zinc-400 font-mono text-xs">Cargando...</p></div>) });

export default function Page() { const { lang } = useLanguage(); const isEs = lang === 'es';
  return (<main className="w-full px-4 sm:px-6 lg:px-8 py-8 flex flex-col items-center justify-start min-h-[calc(100vh-100px)] bg-[#09090b]"><div className="w-full max-w-7xl"><PdfMerger />
    <div className="space-y-8 text-zinc-300 font-sans border-t border-white/10 pt-10 mt-10">
      <div className="bg-[#09090b] border border-white/10 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-white/10 pb-4"><div className="bg-zinc-900 p-2.5 rounded-xl border border-white/10"><Merge className="w-5 h-5 text-white" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'1. Cómo unir PDFs':'1. How to merge PDFs'}</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{[{step:'01',es:'Sube los archivos PDF a la zona de carga.',en:'Upload PDF files to the upload zone.'},{step:'02',es:'Arrastra y suelta documentos en la lista para definir el orden.',en:'Drag and drop documents in the list to define the order.'},{step:'03',es:'Configura separadores, numeración y rango de páginas.',en:'Configure separators, numbering, and page ranges.'},{step:'04',es:'Haz clic en "Unir PDFs →" y descarga el documento combinado.',en:'Click "Merge PDFs →" and download the combined document.'}].map((item,i)=>(<div key={i} className="bg-zinc-900/60 border border-white/5 rounded-xl p-4 flex flex-col gap-2"><span className="text-[10px] font-mono font-bold text-zinc-400 bg-zinc-900 border border-white/10 px-2 py-0.5 rounded-full w-fit">Paso {item.step}</span><p className="text-xs text-zinc-400 leading-relaxed">{isEs?item.es:item.en}</p></div>))}</div></div>
      <div className="bg-[#09090b] border border-amber-500/20 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-amber-500/20 pb-4"><div className="bg-amber-500/10 p-2.5 rounded-xl border border-amber-500/30"><AlertTriangle className="w-5 h-5 text-amber-400" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'2. Limitaciones y consejos útiles':'2. Limitations & useful tips'}</h2></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="space-y-3"><h4 className="text-xs font-mono text-emerald-400 font-bold uppercase tracking-wider border-b border-white/10 pb-2">✓ {isEs?'LO QUE PUEDES HACER':'WHAT YOU CAN DO'}</h4>{[isEs?'Unir múltiples archivos PDF en un solo documento.':'Merge multiple PDF files into one document.',isEs?'Reordenar documentos arrastrando y soltando.':'Reorder documents by dragging and dropping.',isEs?'Insertar páginas en blanco o carátulas como separadores.':'Insert blank pages or cover sheets as separators.',isEs?'Añadir numeración continua en todo el documento.':'Add continuous page numbering throughout the document.'].map((t,i)=>(<div key={i} className="flex items-start gap-2 text-xs text-zinc-300"><span className="text-emerald-400 font-bold flex-shrink-0 mt-0.5">✓</span><span>{t}</span></div>))}</div><div className="space-y-3"><h4 className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider border-b border-white/10 pb-2">💡 {isEs?'CONSEJOS':'TIPS'}</h4>{[isEs?'Ideal para combinar facturas, expedientes o informes en un solo archivo.':'Ideal for combining invoices, records, or reports into one file.',isEs?'Sin límite de archivos. El límite lo define la RAM de tu equipo.':'No file limit. The limit is your device\'s RAM.',isEs?'La fusión preserva calidad original sin recodificación.':'Merging preserves original quality without re-encoding.',isEs?'Si un PDF tiene contraseña, usa "Desbloquear PDF" primero.':'If a PDF has a password, use "Unlock PDF" first.'].map((t,i)=>(<div key={i} className="flex items-start gap-2 text-xs text-zinc-300"><span className="text-amber-400 flex-shrink-0 mt-0.5">→</span><span>{t}</span></div>))}</div></div></div>
      <div className="bg-[#09090b] border border-emerald-500/20 rounded-2xl p-6 sm:p-8 shadow-2xl"><div className="flex items-center gap-3 mb-5 border-b border-emerald-500/20 pb-4"><div className="bg-emerald-500/10 p-2.5 rounded-xl border border-emerald-500/30"><ShieldCheck className="w-5 h-5 text-emerald-400" /></div><h2 className="text-lg font-bold text-white tracking-tight">{isEs?'3. ¿Qué sucede con tus documentos al unirlos?':'3. What happens to your documents when merging?'}</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs text-zinc-400 leading-relaxed"><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">🖥️ {isEs?'Procesamiento 100% local':'100% local processing'}</strong><p className="text-[11px]">{isEs?'La fusión se ejecuta en la RAM. Tus documentos nunca salen de tu equipo.':'Merging runs in your RAM. Your documents never leave your device.'}</p></div><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">📄 {isEs?'Fusión sin pérdida de calidad':'Lossless merge'}</strong><p className="text-[11px]">{isEs?'Documentos combinados con copyPages(). Imágenes, fuentes y vectores intactos.':'Documents combined with copyPages(). Images, fonts, and vectors intact.'}</p></div><div className="bg-zinc-900/60 p-4 rounded-xl border border-white/5 space-y-1.5"><strong className="text-white font-bold text-xs block">📥 {isEs?'Descarga directa y segura':'Direct & secure download'}</strong><p className="text-[11px]">{isEs?'El PDF se genera localmente. Tus originales no se modifican.':'The PDF is generated locally. Your originals are not modified.'}</p></div></div></div>
    </div>
  </div></main>);
}